/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 chemistry.glb -t 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['500ml']: THREE.Mesh
    ['500ml_liquid']: THREE.Mesh
    ['250ml']: THREE.Mesh
    ['250ml_liquid']: THREE.Mesh
    ['125ml']: THREE.Mesh
    ['125ml_liquid']: THREE.Mesh
    Cube001: THREE.Mesh
    Cylinder002: THREE.Mesh
    Cylinder003: THREE.Mesh
    Cylinder005: THREE.Mesh
    Cylinder007: THREE.Mesh
    Cylinder010: THREE.Mesh
    Cylinder011: THREE.Mesh
    Cylinder021: THREE.Mesh
    Cylinder022: THREE.Mesh
    Cylinder023: THREE.Mesh
    Cylinder024: THREE.Mesh
    Cylinder025: THREE.Mesh
    Cylinder026: THREE.Mesh
    Cylinder018: THREE.Mesh
    Cylinder016_1: THREE.Mesh
    Cylinder016_2: THREE.Mesh
    Cylinder020: THREE.Mesh
    Cylinder014: THREE.Mesh
    Cylinder015: THREE.Mesh
    Cylinder033: THREE.Mesh
    Cylinder033_1: THREE.Mesh
    Cylinder027: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder004: THREE.Mesh
    Funnel: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshPhysicalMaterial
    [' 0 Liquid ']: THREE.MeshPhysicalMaterial
    ['Material.004']: THREE.MeshPhysicalMaterial
    ['Material.002']: THREE.MeshPhysicalMaterial
    Material: THREE.MeshStandardMaterial
    Glass: THREE.MeshStandardMaterial
    ['Red Liquid']: THREE.MeshPhysicalMaterial
    ['Pink Liquid']: THREE.MeshStandardMaterial
    ['Yellow Liquid']: THREE.MeshStandardMaterial
    ['Light Green']: THREE.MeshPhysicalMaterial
    ['Dark Green']: THREE.MeshPhysicalMaterial
    [' Blue Liquid']: THREE.MeshPhysicalMaterial
    ['Light Green.001']: THREE.MeshPhysicalMaterial
    ['Material.005']: THREE.MeshPhysicalMaterial
    ['Red Liquid.001']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshPhysicalMaterial
    Water: THREE.MeshPhysicalMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/chemistry.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['500ml'].geometry} material={materials['Material.001']} position={[-0.095, 0.434, 0.805]} rotation={[0, 1.188, 0]} scale={-0.183} />
      <mesh geometry={nodes['500ml_liquid'].geometry} material={materials[' 0 Liquid ']} position={[-0.095, 0.418, 0.806]} rotation={[0, 1.188, 0]} scale={-0.181} />
      <mesh geometry={nodes['250ml'].geometry} material={materials['Material.004']} position={[-0.213, 0.252, 0.357]} rotation={[-Math.PI, -1.188, -Math.PI]} scale={-0.126} />
      <mesh geometry={nodes['250ml_liquid'].geometry} material={materials[' 0 Liquid ']} position={[-0.213, 0.24, 0.356]} rotation={[-Math.PI, -1.188, -Math.PI]} scale={-0.125} />
      <mesh geometry={nodes['125ml'].geometry} material={materials['Material.002']} position={[-0.311, 0.24, -0.017]} rotation={[-Math.PI, -1.188, -Math.PI]} scale={-0.063} />
      <mesh geometry={nodes['125ml_liquid'].geometry} material={materials[' 0 Liquid ']} position={[-0.311, 0.234, -0.017]} rotation={[-Math.PI, -1.188, -Math.PI]} scale={-0.063} />
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[-0.042, 0.418, -0.034]} rotation={[-Math.PI / 2, 0, -2.885]} scale={[0.096, -0.012, 0.214]} />
      <mesh geometry={nodes.Cylinder002.geometry} material={materials.Glass} position={[-0.076, 0.569, -0.144]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder003.geometry} material={materials.Glass} position={[-0.108, 0.569, -0.269]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder005.geometry} material={materials.Glass} position={[-0.14, 0.569, -0.39]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder007.geometry} material={materials.Glass} position={[-0.172, 0.569, -0.514]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder010.geometry} material={materials.Glass} position={[-0.204, 0.569, -0.636]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder011.geometry} material={materials.Glass} position={[-0.237, 0.569, -0.76]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder021.geometry} material={materials['Red Liquid']} position={[-0.076, 0.569, -0.144]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder022.geometry} material={materials['Pink Liquid']} position={[-0.108, 0.569, -0.269]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder023.geometry} material={materials['Yellow Liquid']} position={[-0.14, 0.569, -0.39]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials['Light Green']} position={[-0.172, 0.569, -0.514]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder025.geometry} material={materials['Dark Green']} position={[-0.204, 0.569, -0.636]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials[' Blue Liquid']} position={[-0.237, 0.569, -0.76]} rotation={[0, -1.315, 0]} scale={0.033} />
      <mesh geometry={nodes.Cylinder018.geometry} material={materials.Glass} position={[0.496, 0.384, -0.041]} rotation={[0, -1.315, 0]} scale={0.151} />
      <group position={[0.496, 1.019, -0.041]} rotation={[0, -1.315, 0]} scale={0.019}>
        <mesh geometry={nodes.Cylinder016_1.geometry} material={materials.Material} />
        <mesh geometry={nodes.Cylinder016_2.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Cylinder020.geometry} material={materials['Light Green.001']} position={[0.496, 0.301, -0.041]} rotation={[0, -1.315, 0]} scale={0.145} />
      <mesh geometry={nodes.Cylinder014.geometry} material={materials.Glass} position={[0.219, 0.301, -0.399]} rotation={[0, -1.315, 0]} scale={[0.019, 0.036, 0.019]} />
      <mesh geometry={nodes.Cylinder015.geometry} material={materials.Material} position={[0.219, 0.402, -0.399]} rotation={[0, -1.315, 0]} scale={[0.021, 0.008, 0.021]} />
      <group position={[-0.381, 0.221, -0.982]} rotation={[Math.PI, -0.901, Math.PI]} scale={[0.076, 0.01, 0.076]}>
        <mesh geometry={nodes.Cylinder033.geometry} material={materials['Material.005']} />
        <mesh geometry={nodes.Cylinder033_1.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cylinder027.geometry} material={materials['Red Liquid.001']} position={[-0.381, 0.221, -0.982]} rotation={[Math.PI, -0.901, Math.PI]} scale={[0.073, 0.01, 0.073]} />
      <mesh geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[0.07, 0.34, -0.853]} rotation={[0, -1.315, 0]} scale={[-0.146, -0.108, -0.146]} />
      <mesh geometry={nodes.Cylinder004.geometry} material={materials.Water} position={[0.07, 0.34, -0.853]} rotation={[0, -1.315, 0]} scale={[-0.144, -0.107, -0.144]} />
      <mesh geometry={nodes.Funnel.geometry} material={materials.Glass} position={[0.211, 0.303, -0.242]} rotation={[0, -1.315, -Math.PI]} scale={0.07} />
    </group>
  )
}

useGLTF.preload('/chemistry.glb')
